server:
  #port: 8080 
  servlet.context-path: /app

spring:
  jackson.property-naming-strategy: SNAKE_CASE
  mvc.dispatch-options-request: true
  ## Vault Configuration ##
  application:
    name: springboot_template
  cloud:
    vault:
      kv:
        enabled: true
      authentication: APPROLE
      app-role:
        role-id: fcbfc5c8-18b9-d5f8-9c8d-a981113e3c12
        secret-id: fed828a1-b1be-b6fe-6a69-64ce4301d887     
      scheme: http
      host: 127.0.0.1
      port: 9200
  config:
    import: vault://

logging.config: classpath:logging/log4j2.xml  


